from flask import Flask, request, jsonify
from flask_cors import CORS
import torch
import torch.nn as nn
import torchvision.transforms as transforms
from PIL import Image
import io

app = Flask(__name__)
CORS(app)
#test
# Define the CNN model class (same as in your training script)
class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=256, kernel_size=3, stride=1, padding=1)
        self.conv2 = nn.Conv2d(in_channels=256, out_channels=512, kernel_size=3, stride=1, padding=1)
        self.conv3 = nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=3, stride=1, padding=1)
        self.conv4 = nn.Conv2d(in_channels=1024, out_channels=4096, kernel_size=3, stride=1, padding=1)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2, padding=0)
        self.fc1 = nn.Linear(in_features=256*8*8, out_features=1024)
        self.fc2 = nn.Linear(in_features=1024, out_features=512)
        self.fc3 = nn.Linear(in_features=512, out_features=9)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p=0.5)

    def forward(self, x):
        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))
        x = self.pool(self.relu(self.conv3(x)))
        x = self.pool(self.relu(self.conv4(x)))
        x = x.view(-1, 256*8*8)  # Flatten the tensor
        x = self.dropout(self.relu(self.fc1(x)))
        x = self.fc2(x)
        x = self.fc3(x)
        return x

# Load the trained model
model = SimpleCNN()
model.load_state_dict(torch.load('/Users/vinil_polepalli/Desktop/gitClones/bite.ai/src/pages/model.pth', weights_only=True))
model.eval()

# Define the image transformation
transform = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])



# Define class names
class_info = {
    "Ant": "An ant bite occurs when an ant uses its mandibles (jaws) to pinch the skin. Depending on the species, ant bites can cause mild discomfort, redness, and swelling. Some ants, like fire ants, also inject venom through a sting, which can lead to intense burning pain, itching, and the formation of small pustules or blisters. In most cases, ant bites are harmless and heal on their own, but severe allergic reactions can occur in some individuals, leading to symptoms like difficulty breathing, dizziness, or swelling in areas away from the bite site, requiring immediate medical attention.",
    "Bed Bug": "Bed bug bites are small, red, itchy bumps that usually appear in clusters or lines on exposed skin areas such as the face, arms, neck, and legs. These nocturnal insects feed on human blood while a person is sleeping, and their bites are typically painless at first but can cause itching, swelling, and irritation hours or days later. Some individuals may experience allergic reactions, leading to larger welts or blisters. Although bed bug bites don't transmit diseases, they can be mistaken for other insect bites, and the presence of bed bugs, their eggs, or small blood stains on bedding often signals an infestation, causing discomfort and anxiety.",
    "Bees": "A bee sting occurs when a bee punctures the skin with its stinger, injecting venom that causes pain, swelling, and redness around the sting site. The initial sensation is a sharp, burning pain, followed by localized swelling and sometimes itching. For most people, the reaction is mild and subsides within a few hours or days. However, some individuals may experience more severe allergic reactions, known as anaphylaxis, which can cause symptoms like difficulty breathing, hives, swelling in areas away from the sting, dizziness, or nausea. In such cases, immediate medical attention is required. Unlike other stinging insects, honeybees leave their stinger in the skin, which should be removed promptly to reduce the spread of venom.",
    "Chigger": "A chigger bite occurs when tiny, larval mites called chiggers attach to the skin and inject digestive enzymes, causing intense itching and red, raised bumps. The bites are typically found in clusters or patches on areas of the body where clothing is tight or where the skin is thin, such as around the waist, ankles, or armpits. Chiggers don’t burrow into the skin but instead feed on skin cells, leaving itchy welts that can take several days to heal. While chigger bites can be uncomfortable, they usually resolve on their own without the need for medical treatment. Preventing chigger bites involves wearing long clothing and using insect repellent when in grassy or wooded areas.",
    "Flea": "Flea bites are small, red, itchy bumps that usually appear in clusters or lines on the skin, particularly on the legs, ankles, and feet. Fleas are tiny, wingless insects that feed on the blood of animals and humans, typically biting multiple times in one area. The bites often cause itching, swelling, and irritation, and scratching them can lead to secondary infections. While flea bites are usually harmless, they can transmit diseases like typhus or plague in rare cases, and some people may have allergic reactions to the bites, resulting in more pronounced symptoms such as hives or rashes. Flea infestations are common in homes with pets and can be controlled through regular pet treatments and thorough cleaning.",
    "Mosquito": "A mosquito bite occurs when a mosquito pierces the skin to feed on blood, injecting saliva that triggers the body's immune response. This results in red, itchy bumps that can swell and become irritated. The itching typically begins shortly after the bite and can last for several days. Most mosquito bites are harmless and resolve on their own, but in some cases, mosquitoes can transmit diseases such as malaria, dengue fever, Zika virus, and West Nile virus. Some individuals may also experience mild allergic reactions to the bites, leading to larger welts or prolonged irritation. Preventing mosquito bites involves using insect repellent, wearing protective clothing, and avoiding areas with high mosquito activity.",
    "No Bite Found": "If there is no visible bite but you still experience itching or skin irritation, it could be due to other factors like allergic reactions, skin conditions (e.g., eczema or contact dermatitis), or environmental irritants (such as soaps, lotions, or plants). In some cases, microscopic pests like dust mites or invisible irritants like dry air can cause itching without leaving a mark. Anxiety or stress can also trigger skin sensations that feel like bites or stings, even when no insects are present. If symptoms persist or worsen, it's advisable to consult a healthcare professional to determine the underlying cause.",
    "Spider": "A spider bite occurs when a spider injects venom into the skin, usually while defending itself. Most bites cause mild reactions like redness, swelling, and itching at the bite site, which typically resolve within a few days. Some spider bites may result in localized pain, blistering, or necrosis, depending on the species. In rare cases, certain spiders, like the black widow or brown recluse, can cause more severe symptoms such as muscle pain, fever, or tissue damage. Most spider bites heal without medical treatment, but it's essential to seek care if the bite worsens or shows signs of infection.",
    "Tick": "A tick bite occurs when a tick latches onto the skin to feed on blood, often going unnoticed due to the tick's small size and painless bite. The area around the bite may become red, swollen, or itchy, but these symptoms are usually mild. However, some ticks can transmit serious diseases such as Lyme disease, Rocky Mountain spotted fever, or ehrlichiosis, making it important to remove the tick as soon as possible. Symptoms of tick-borne illnesses, such as fever, fatigue, or a rash, may appear days or weeks after the bite. Preventing tick bites involves wearing protective clothing, using tick repellents, and checking for ticks after spending time in grassy or wooded areas."
}


# Define custom descriptions for each bug bite type
class_descriptions = {
    "Ant": "In New Jersey, ant bites are often caused by species like the black carpenter ant or the smaller pavement ant. These bites typically result in a small red bump and may cause minor swelling or itching. For most people, ant bites are harmless, but they can sometimes lead to infections if scratched excessively. However, fire ants, though not native to New Jersey, are an increasing concern due to their painful bites and stings, which can cause severe allergic reactions or even anaphylaxis in some individuals. One aspect the bite.ai algorithm focuses on is the detailed pattern of the bite area. It analyzes the size, shape, and arrangement of the bites, distinguishing between single bites or multiple clustered bites that are characteristic of ant infestations. The AI also checks for any skin irritation, blisters, or signs of secondary infection such as redness and swelling that extend beyond the bite site. Importantly, it screens for allergic reactions by analyzing the color of the skin and the level of inflammation, which may indicate more serious issues like anaphylactic responses. While ant bites rarely transmit diseases, maintaining awareness of symptoms like fever, excessive swelling, or increased pain is crucial. Such symptoms may suggest secondary bacterial infections, such as cellulitis, which require medical attention. The bite.ai algorithm is designed to assist in recognizing these early warning signs, helping users differentiate between common bites and those that might need professional care.",
    "Bed Bug": "In New Jersey, bed bug bites are a common nuisance, especially in urban areas with dense populations. These bites typically occur at night, leaving small, red, itchy welts that often appear in clusters or linear patterns on exposed skin like the arms, neck, and face. While bed bugs don't transmit diseases, their bites can cause intense itching, allergic reactions, and, in some cases, secondary infections from excessive scratching. To mitigate bed bug bites, preventive measures like using protective mattress covers, regularly inspecting bedding, and reducing clutter where bugs can hide are crucial. The **bite.ai** algorithm assists in identifying bed bug bites by analyzing key features such as the bite pattern—whether in clusters or straight lines—and evaluating redness, swelling, or irritation around the affected area. It also checks for signs of more severe allergic reactions, like blistering or intense inflammation. Although bed bugs are not known to spread diseases, the AI is designed to detect early signs of secondary complications, such as cellulitis, by assessing the surrounding skin for warmth, redness, and abnormal swelling. The insights provided help users understand the nature of the bite and guide them on whether medical intervention might be necessary for infections or allergic responses, while also providing advice on how to prevent future bites.",
    "Bees": "In New Jersey, bee stings are a common occurrence, especially during warmer months when bees are most active. A typical bee sting results in a sharp pain, followed by redness, swelling, and a small raised welt at the sting site. For most individuals, the discomfort subsides within a few hours, but some people may experience more severe reactions. If you're stung by a bee, it’s important to remove the stinger as quickly as possible to reduce venom exposure and wash the area with soap and water. Applying ice can help reduce swelling and pain. However, bee stings can trigger allergic reactions in certain individuals, ranging from mild to severe. Symptoms of an allergic reaction include increased swelling, hives, difficulty breathing, and in extreme cases, anaphylaxis—a life-threatening condition requiring immediate medical attention. The bite.ai algorithm is designed to help users quickly identify and assess bee stings by analyzing the size of the sting area, the level of swelling, and any surrounding redness. It can also detect early signs of an allergic reaction by evaluating skin changes, such as the spread of hives, or abnormal swelling. The AI also provides guidance on whether medical attention is required. If symptoms like dizziness, difficulty breathing, or excessive swelling occur, the algorithm advises seeking emergency care, as these are signs of a serious allergic reaction. For non-severe cases, the AI may suggest home remedies such as using antihistamines, applying hydrocortisone cream, or following up with a healthcare provider if the symptoms persist or worsen",
    "Chigger": "In New Jersey, chigger bites are a frequent issue during the warmer months, particularly in grassy or wooded areas. Chiggers, which are the larval form of mites, attach themselves to the skin and inject digestive enzymes that cause intense itching and small, red, raised bumps. The bites often appear in clusters around areas where clothing fits tightly, such as the waist, ankles, and underarms. Although chigger bites do not transmit diseases, the intense itching can lead to scratching, which may cause secondary infections. To mitigate the effects of chigger bites, it’s essential to wash the affected area with soap and water immediately after potential exposure. Applying anti-itch creams or taking antihistamines can reduce discomfort. Wearing long sleeves, pants, and using insect repellents with DEET can help prevent bites. The bite.ai algorithm analyzes several characteristics of chigger bites, including their clustered appearance and the skin's reaction, such as redness and swelling. It also evaluates the intensity of the irritation and the risk of secondary infections if the skin appears damaged from scratching. The AI provides advice on home treatments like cold compresses, calamine lotion, or hydrocortisone cream to reduce inflammation and itching. In terms of medical advice, while chigger bites generally don’t require professional care, the AI monitors for signs of infection, such as increased redness, warmth, pus, or fever. If these symptoms are detected, it advises users to seek medical attention to prevent more serious skin infections.",
    "Flea": "In New Jersey, flea bites are common, particularly for people with pets or in areas with high wildlife populations. Fleas usually bite around the ankles, legs, or other exposed areas, causing small, red, itchy bumps that often appear in clusters or lines. The bites can be extremely itchy, and scratching them can lead to skin infections. While fleas are primarily a nuisance, they can occasionally transmit diseases, such as murine typhus and, more rarely, tapeworms or the plague, though the latter is extremely uncommon in New Jersey. To mitigate flea bites, it’s important to regularly treat pets with flea preventatives, vacuum carpets and furniture frequently, and wash pet bedding in hot water. Wearing long clothing and using insect repellents containing DEET can also help prevent bites. If bitten, cleaning the affected area with soap and water, applying anti-itch creams, and using antihistamines can reduce itching and inflammation. The bite.ai algorithm helps users identify flea bites by analyzing key features such as the pattern (clusters or lines) and specific characteristics of the skin, including redness, swelling, and any signs of irritation. The AI evaluates the likelihood of secondary infections caused by scratching and offers advice on how to prevent complications. For most flea bites, home care is sufficient, but if symptoms like fever, rash, or pus-filled blisters appear, the AI may recommend seeking medical attention, as these could indicate a bacterial infection or an allergic reaction that requires further treatment.",
    "Mosquito": "In New Jersey, mosquito bites are a common nuisance, particularly during the warmer months and near standing water where mosquitoes breed. A typical mosquito bite results in a small, red, itchy bump that can vary in size and may last for several days. While most mosquito bites cause only mild discomfort, they can sometimes transmit diseases, including West Nile virus, Eastern equine encephalitis (EEE), and Zika virus, although these are relatively rare in the region. To mitigate the effects of mosquito bites, it’s essential to use insect repellents containing DEET, wear long sleeves and pants, and avoid outdoor activities during peak mosquito activity times, typically dawn and dusk. Additionally, eliminating standing water around homes can help reduce mosquito populations. The bite.ai algorithm analyzes various characteristics of mosquito bites, such as the size of the bump, the level of redness, and any associated symptoms like swelling or blisters. It can distinguish between normal reactions and those that may indicate an allergic response or infection. The AI also monitors for early signs of mosquito-borne diseases by assessing symptoms like fever, headache, or unusual fatigue. For typical mosquito bites, the algorithm recommends home care measures, such as applying anti-itch creams, taking antihistamines, and using cold compresses to alleviate discomfort. However, if users experience severe symptoms or signs of illness, such as persistent fever, muscle pain, or neurological symptoms, the AI advises seeking medical attention promptly to rule out more serious conditions.",
    "No Bite Found": "If there is no visible bite but symptoms such as itching, redness, or irritation are present, it may still be related to insect exposure or an allergic reaction to environmental factors like dust mites, plant allergens, or chemical irritants. Sometimes, insects like fleas or bed bugs leave only subtle marks, or the body’s reaction is delayed, making the bite difficult to see. Additionally, skin conditions such as eczema, hives, or contact dermatitis can mimic the symptoms of an insect bite, causing similar discomfort without an actual bite being present. The bite.ai algorithm is designed to analyze skin irritations even in the absence of a visible bite mark. It assesses patterns of redness, swelling, and other symptoms like itching or skin texture changes to help determine the likely cause. If no clear bite is detected, the AI might suggest potential causes such as allergic reactions or irritation from environmental factors. It can also recommend over-the-counter treatments like antihistamines, topical creams, or avoiding suspected irritants. In more severe cases, such as when the irritation spreads, becomes painful, or is accompanied by symptoms like fever or hives, the AI may advise seeking medical attention to rule out allergic reactions or underlying skin conditions.",
    "Spider": "In New Jersey, spider bites are relatively rare, as most spiders are not aggressive and bite only in self-defense. Common species like the wolf spider or garden spider usually cause mild reactions, resulting in small, red, itchy, or slightly swollen spots that resemble other insect bites. However, bites from more venomous spiders, like the black widow or brown recluse, though less common in New Jersey, can lead to more serious symptoms. These bites may cause intense pain, muscle cramps, fever, and, in severe cases, necrosis of the skin. For mild spider bites, washing the area with soap and water, applying ice, and using over-the-counter anti-itch creams or pain relievers can help manage symptoms. However, more serious bites, particularly those suspected to be from a venomous spider, require immediate medical attention. Symptoms to watch for include severe pain at the bite site, spreading redness or swelling, muscle pain, fever, or the development of blisters or dead skin tissue. The bite.ai algorithm can help users differentiate between common spider bites and those that may require medical care. It analyzes the bite’s characteristics, such as size, color, and any surrounding symptoms like spreading redness, blistering, or tissue damage. The AI can flag concerning features, such as necrosis or systemic symptoms like fever, and recommend prompt medical attention if venomous bites are suspected. For mild cases, the AI suggests at-home remedies like antihistamines and cold compresses, while offering guidance on when to seek professional care based on symptom progression or severity.",
    "Tick": "In New Jersey, tick bites are a common concern, especially in wooded or grassy areas. Ticks attach themselves to the skin and feed on blood, often going unnoticed for hours or even days. Tick bites themselves are usually painless and may result in a small red bump, but the bigger concern is the potential transmission of diseases such as Lyme disease, anaplasmosis, or babesiosis, which are common in the region. One key sign of Lyme disease is the development of a 'bull's-eye' rash (erythema migrans) that can appear days or even weeks after the bite. If bitten by a tick, it’s important to remove the tick as quickly as possible using fine-tipped tweezers, ensuring the entire tick is extracted. Wash the area with soap and water, and apply an antiseptic. To mitigate the risk of tick bites, wearing long sleeves and pants, using insect repellents with DEET, and performing full-body checks after outdoor activities can significantly reduce the chances of being bitten. The bite.ai algorithm aids in identifying tick bites by analyzing the bite site for characteristics such as redness, swelling, and the presence of a tick or remnants of one. It also monitors for more serious symptoms like the development of a rash or flu-like symptoms, which may indicate tick-borne illnesses. The AI provides advice on removing ticks and suggests monitoring for signs of Lyme disease, including joint pain, fatigue, or the appearance of the bull’s-eye rash. If these symptoms are present, the AI recommends seeking medical attention promptly, as early treatment with antibiotics is crucial to prevent the progression of Lyme disease and other tick-borne illnesses."
}


@app.route('/predict', methods=['POST'])
def predict():
    if 'file' not in request.files:
        return jsonify({'error': 'No file provided'}), 400

    file = request.files['file']
    if file.filename == '':
        return jsonify({'error': 'No file selected'}), 400

    try:
        img = Image.open(io.BytesIO(file.read()))
        img = transform(img).unsqueeze(0)  # Transform and add batch dimension
        with torch.no_grad():
            outputs = model(img)
            _, predicted = torch.max(outputs, 1)
            class_idx = predicted.item()
            class_name = ["Ant", "Bed Bug", "Bees", "Chigger","Flea", "Mosquito","No Bite Found", "Spider", "Tick"][class_idx]  # Map class_idx to class name

        return jsonify({
            'class': class_name,
            'description': class_info[class_name],
            'custom_description': class_descriptions[class_name]
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True, port=5001)